# Generated by Django 4.2.30 on 2026-06-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_participant',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Participa (se logueó)'),
        ),
    ]
