# Generated by Django 4.2.30 on 2026-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_is_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
