# Generated by Django 4.2.30 on 2026-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_activation_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=200)),
                ('email_host', models.CharField(blank=True, max_length=200)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('email_host_user', models.CharField(blank=True, max_length=200)),
                ('email_host_password', models.CharField(blank=True, max_length=200)),
                ('default_from_email', models.CharField(blank=True, max_length=200)),
                ('football_data_token', models.CharField(blank=True, max_length=200)),
                ('football_data_base_url', models.URLField(default='https://api.football-data.org/v4/')),
                ('world_cup_competition_code', models.CharField(default='WC', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
