# Generated by Django 4.2.30 on 2026-06-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('flag_url', models.URLField(blank=True, max_length=300, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('stage', models.CharField(blank=True, max_length=40, null=True)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('matchday', models.IntegerField(blank=True, null=True)),
                ('utc_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('TIMED', 'Timed'), ('IN_PLAY', 'In play'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished'), ('SUSPENDED', 'Suspended'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, choices=[('HOME_TEAM', 'Home team'), ('AWAY_TEAM', 'Away team'), ('DRAW', 'Draw')], max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='matches.team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='matches.team')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['utc_date', 'id'],
            },
        ),
    ]
