# Generated by Django 4.2.30 on 2026-06-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('EXTRA_TIME', 'Extra time'), ('PENALTY_SHOOTOUT', 'Penalty shootout')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalties_home',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
