# Generated by Django 4.2.30 on 2026-06-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_duration_match_penalties_away_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='extra_time_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='extra_time_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='half_time_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='half_time_home',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='regular_time_away',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='regular_time_home',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
